customhost = "employee.ch8asacocdcd.ap-south-1.rds.amazonaws.com"
customuser = "nupoor"
custompass = "12345678"
customdb = "employee"
custombucket = "nupoor-employeedatabase"
customregion = "ap-south-1"
